name: 'Package Pushed'

on:
    push:
        branches:
            - master
            - v3
        paths:
            - packages/**

jobs:
    build-pkg:
        name: Build package
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Login to GitHub registry
              uses: docker/login-action@v1
              with:
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  registry: docker.pkg.github.com

            - name: Get list of changed files
              uses: lots0logs/gh-action-get-changed-files@2.1.4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Build Packages
              run: |
                  PACKAGES="file-0.0.1 forte-1.0.0 freebasic-1.8.0 gawk-5.1.0 gcc-10.2.0 go-1.16.2 golfscript-1.0.0 groovy-3.0.7 haskell-9.0.1 husk-1.0.0 iverilog-11.0.0 japt-2.0.0 java-15.0.2 jelly-0.1.31 julia-1.5.4 julia-1.6.1 kotlin-1.4.31 lisp-2.1.2 llvm_ir-12.0.1 lolcode-0.11.2 lua-5.4.2 mono-6.12.0 nasm-2.15.5 nim-1.4.4"
                  echo "Packages: $PACKAGES"
                  docker pull docker.pkg.github.com/luj8n/piston/repo-builder:latest
                  docker build -t repo-builder repo
                  docker run -v "${{ github.workspace }}:/piston" repo-builder --no-server $PACKAGES
                  ls -la packages

            - name: Upload Packages
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: packages/*.pkg.tar.gz
                  tag: pkgs
                  overwrite: true
                  file_glob: true
    create-index:
        name: Create Index
        runs-on: ubuntu-latest
        needs: build-pkg
        steps:
            - name: 'Download all release assets'
              run: curl -s https://api.github.com/repos/luj8n/piston/releases/latest | jq '.assets[].browser_download_url' -r | xargs -L 1 curl -sLO
            - name: 'Generate index file'
              run: |
                  echo "" > index
                  BASEURL=https://github.com/luj8n/piston/releases/download/pkgs/
                  for pkg in *.pkg.tar.gz
                  do
                    PKGFILE=$(basename $pkg)
                    PKGFILENAME=$(echo $PKGFILE | sed 's/\.pkg\.tar\.gz//g')

                    PKGNAME=$(echo $PKGFILENAME | grep -oP '^\K.+(?=-)')
                    PKGVERSION=$(echo $PKGFILENAME | grep -oP '^.+-\K.+')
                    PKGCHECKSUM=$(sha256sum $PKGFILE | awk '{print $1}')
                    echo "$PKGNAME,$PKGVERSION,$PKGCHECKSUM,$BASEURL$PKGFILE" >> index
                    echo "Adding package $PKGNAME-$PKGVERSION"
                  done
            - name: Upload index
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: index
                  tag: pkgs
                  overwrite: true
                  file_glob: true
